package com.legue.axel.lolsummonertool.database.model.match

import androidx.annotation.NonNull
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.ForeignKey.CASCADE
import androidx.room.PrimaryKey

@Entity(tableName = "participantStats", foreignKeys = [ForeignKey(entity = Participant::class, parentColumns = ["id"], childColumns = ["participantKey"], onDelete = CASCADE)])
data class ParticipantStat(
        @PrimaryKey(autoGenerate = true)
        @NonNull
        val id: Int,
        val firstBloodAssist: Boolean? = null,
        val visionScore: Long? = null,
        val magicDamageDealtToChampions: Long? = null,
        val damageDealtToObjectives: Long? = null,
        val totalTimeCrowdControlDealt: Int? = null,
        val longestTimeSpentLiving: Int? = null,
        val perk1Var1: Int? = null,
        val perk1Var3: Int? = null,
        val perk1Var2: Int? = null,
        val tripleKills: Int? = null,
        val perk3Var3: Int? = null,
        val nodeNeutralizeAssist: Int? = null,
        val perk3Var2: Int? = null,
        val playerScore9: Int? = null,
        val playerScore8: Int? = null,
        val kills: Int? = null,
        val playerScore1: Int? = null,
        val playerScore0: Int? = null,
        val playerScore3: Int? = null,
        val playerScore2: Int? = null,
        val playerScore5: Int? = null,
        val playerScore4: Int? = null,
        val playerScore7: Int? = null,
        val playerScore6: Int? = null,
        val perk5Var1: Int? = null,
        val perk5Var3: Int? = null,
        val perk5Var2: Int? = null,
        val totalScoreRank: Int? = null,
        val neutralMinionsKilled: Int? = null,
        val damageDealtToTurrets: Long? = null,
        val physicalDamageDealtToChampions: Long? = null,
        val nodeCapture: Int? = null,
        val largestMultiKill: Int? = null,
        val perk2Var2: Int? = null,
        val perk2Var3: Int? = null,
        val totalUnitsHealed: Int? = null,
        val perk2Var1: Int? = null,
        val perk4Var1: Int? = null,
        val perk4Var2: Int? = null,
        val perk4Var3: Int? = null,
        val wardsKilled: Int? = null,
        val largestCriticalStrike: Int? = null,
        val largestKillingSpree: Int? = null,
        val quadraKills: Int? = null,
        val teamObjective: Int? = null,
        val magicDamageDealt: Long? = null,
        val item2: Int? = null,
        val item3: Int? = null,
        val item0: Int? = null,
        val neutralMinionsKilledTeamJungle: Int? = null,
        val item6: Int? = null,
        val item4: Int? = null,
        val item5: Int? = null,
        val perk1: Int? = null,
        val perk0: Int? = null,
        val perk3: Int? = null,
        val perk2: Int? = null,
        val perk5: Int? = null,
        val perk4: Int? = null,
        val perk3Var1: Int? = null,
        val damageSelfMitigated: Long? = null,
        val magicalDamageTaken: Long? = null,
        val firstInhibitorKill: Boolean? = null,
        val trueDamageTaken: Long? = null,
        val nodeNeutralize: Int? = null,
        val assists: Int? = null,
        val combatPlayerScore: Int? = null,
        val perkPrimaryStyle: Int? = null,
        val goldSpent: Int? = null,
        val trueDamageDealt: Long? = null,
        val participantId: Int? = null,
        val totalDamageTaken: Long? = null,
        val physicalDamageDealt: Long? = null,
        val sightWardsBoughtInGame: Int? = null,
        val totalDamageDealtToChampions: Long? = null,
        val physicalDamageTaken: Long? = null,
        val totalPlayerScore: Int? = null,
        val win: Boolean? = null,
        val objectivePlayerScore: Int? = null,
        val totalDamageDealt: Long? = null,
        val item1: Int? = null,
        val neutralMinionsKilledEnemyJungle: Int? = null,
        val deaths: Int? = null,
        val wardsPlaced: Int? = null,
        val perkSubStyle: Int? = null,
        val turretKills: Int? = null,
        val firstBloodKill: Boolean? = null,
        val trueDamageDealtToChampions: Long? = null,
        val goldEarned: Int? = null,
        val killingSprees: Int? = null,
        val unrealKills: Int? = null,
        val altarsCaptured: Int? = null,
        val firstTowerAssist: Boolean? = null,
        val firstTowerKill: Boolean? = null,
        val champLevel: Int? = null,
        val doubleKills: Int? = null,
        val nodeCaptureAssist: Int? = null,
        val inhibitorKills: Int? = null,
        val firstInhibitorAssist: Boolean? = null,
        val perk0Var1: Int? = null,
        val perk0Var2: Int? = null,
        val perk0Var3: Int? = null,
        val visionWardsBoughtInGame: Int? = null,
        val altarsNeutralized: Int? = null,
        val pentaKills: Int? = null,
        val totalHeal: Long? = null,
        val totalMinionsKilled: Int? = null,
        val timeCCingOthers: Long? = null,
        @ColumnInfo(index = true)
        var participantKey: Int? = null
) 
